import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Rubik } from "next/font/google";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "500", "700"],
  variable: "--font-rubik",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${rubik.variable} antialiased font-sans`}>
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
